### ISSUE TITLE
yarn dev task is broken 😢 

### ISSUE THREAD

**Issue by langz** [dnbexperience/eufemia#1912]
## 🐛 Bug Report

`yarn dev` doesn't work 😿

I believe it could be related to https://github.com/dnbexperience/eufemia/pull/1833

## To Reproduce

Run `yarn dev`

Produces:

```bash
➜  eufemia git:(v10) ✗ yarn dev
info @storybook/react v6.5.12
info 
(node:16145) DeprecationWarning: --static-dir CLI flag is deprecated, see:

https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated---static-dir-cli-flag
(Use `node --trace-deprecation ...` to show where the warning was created)
info => Loading presets
info => Serving static files from / at /
info => Loading custom babel config as JS
info => Loading custom manager config
info => Loading custom manager config
info => Using implicit CSS loaders
info => Using default Webpack5 setup
ERR! Error: For the selected environment is no default script chunk format available:
ERR! JSONP Array push can be chosen when 'document' or 'importScripts' is available.
ERR! CommonJs exports can be chosen when 'require' or node builtins are available.
ERR! Make sure that your 'browserslist' includes only platforms that support these features or select an appropriate 'target' to allow selecting a chunk format by default. Alternatively specify the 'output.chunkFormat' directly.
ERR!     at /Users/anderslangseth/dev/eufemia/node_modules/webpack/lib/config/defaults.js:814:11
ERR!     at F (/Users/anderslangseth/dev/eufemia/node_modules/webpack/lib/config/defaults.js:73:15)
ERR!     at applyOutputDefaults (/Users/anderslangseth/dev/eufemia/node_modules/webpack/lib/config/defaults.js:795:2)
ERR!     at applyWebpackOptionsDefaults (/Users/anderslangseth/dev/eufemia/node_modules/webpack/lib/config/defaults.js:196:2)
ERR!     at createCompiler (/Users/anderslangseth/dev/eufemia/node_modules/webpack/lib/webpack.js:77:2)
ERR!     at create (/Users/anderslangseth/dev/eufemia/node_modules/webpack/lib/webpack.js:134:16)
ERR!     at webpack (/Users/anderslangseth/dev/eufemia/node_modules/webpack/lib/webpack.js:158:32)
ERR!     at f (/Users/anderslangseth/dev/eufemia/node_modules/webpack/lib/index.js:63:16)
ERR!     at starterGeneratorFn (/Users/anderslangseth/dev/eufemia/node_modules/@storybook/builder-webpack5/dist/cjs/index.js:118:18)
ERR!     at starterGeneratorFn.next (<anonymous>)
ERR!     at Object.start (/Users/anderslangseth/dev/eufemia/node_modules/@storybook/builder-webpack5/dist/cjs/index.js:272:34)
ERR!     at async Promise.all (index 0)
ERR!     at async storybookDevServer (/Users/anderslangseth/dev/eufemia/node_modules/@storybook/core-server/dist/cjs/dev-server.js:207:28)
ERR!     at async buildDevStandalone (/Users/anderslangseth/dev/eufemia/node_modules/@storybook/core-server/dist/cjs/build-dev.js:120:31)
ERR!     at async buildDev (/Users/anderslangseth/dev/eufemia/node_modules/@storybook/core-server/dist/cjs/build-dev.js:174:5)
ERR!  Error: For the selected environment is no default script chunk format available:
ERR! JSONP Array push can be chosen when 'document' or 'importScripts' is available.
ERR! CommonJs exports can be chosen when 'require' or node builtins are available.
ERR! Make sure that your 'browserslist' includes only platforms that support these features or select an appropriate 'target' to allow selecting a chunk format by default. Alternatively specify the 'output.chunkFormat' directly.
ERR!     at /Users/anderslangseth/dev/eufemia/node_modules/webpack/lib/config/defaults.js:814:11
ERR!     at F (/Users/anderslangseth/dev/eufemia/node_modules/webpack/lib/config/defaults.js:73:15)
ERR!     at applyOutputDefaults (/Users/anderslangseth/dev/eufemia/node_modules/webpack/lib/config/defaults.js:795:2)
ERR!     at applyWebpackOptionsDefaults (/Users/anderslangseth/dev/eufemia/node_modules/webpack/lib/config/defaults.js:196:2)
ERR!     at createCompiler (/Users/anderslangseth/dev/eufemia/node_modules/webpack/lib/webpack.js:77:2)
ERR!     at create (/Users/anderslangseth/dev/eufemia/node_modules/webpack/lib/webpack.js:134:16)
ERR!     at webpack (/Users/anderslangseth/dev/eufemia/node_modules/webpack/lib/webpack.js:158:32)
ERR!     at f (/Users/anderslangseth/dev/eufemia/node_modules/webpack/lib/index.js:63:16)
ERR!     at starterGeneratorFn (/Users/anderslangseth/dev/eufemia/node_modules/@storybook/builder-webpack5/dist/cjs/index.js:118:18)
ERR!     at starterGeneratorFn.next (<anonymous>)
ERR!     at Object.start (/Users/anderslangseth/dev/eufemia/node_modules/@storybook/builder-webpack5/dist/cjs/index.js:272:34)
ERR!     at async Promise.all (index 0)
ERR!     at async storybookDevServer (/Users/anderslangseth/dev/eufemia/node_modules/@storybook/core-server/dist/cjs/dev-server.js:207:28)
ERR!     at async buildDevStandalone (/Users/anderslangseth/dev/eufemia/node_modules/@storybook/core-server/dist/cjs/build-dev.js:120:31)
ERR!     at async buildDev (/Users/anderslangseth/dev/eufemia/node_modules/@storybook/core-server/dist/cjs/build-dev.js:174:5)

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.

```

## Eufemia Version

Type `Eufemia.version` in your browser console and include it here.

**Comment by tujoworker** [comment]
Yes, you are right, `maintained node versions` [means](https://browserslist.dev/?q=bWFpbnRhaW5lZCBub2RlIHZlcnNpb25z) `14.20.0` while we are using `14.17.0`. But this does not fix the issue. It looks like its something [Storybook/Webpack](https://github.com/storybookjs/storybook/issues/15882) related.

I think, we may actually remove `maintained node versions`, because we do not really use it.
